apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.crd.pluralName }}.{{ .Values.crd.group }}
spec:
  group: {{ .Values.crd.group }}
  scope: {{ .Values.crd.scope }}
  versions:
    - name: {{ .Values.crd.version }}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                valueType:
                  type: string
                  enum:
                    - YAML
                    - PROPERTIES
                    - KV
                value:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                host:
                  type: string
                path:
                  type: string
  names:
    plural: {{ .Values.crd.pluralName }}
    singular: {{ .Values.crd.singularName}}
    kind: {{.Values.crd.kind }}
    shortNames:
      - {{ .Values.crd.singularName}}
