apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.role.name }}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "create", "get", "list", "watch", "delete", "deletecollection", "patch" ]
  - apiGroups: [{{ .Values.crd.group | quote }}]
    resources: [ {{ .Values.crd.pluralName | quote }}]
    verbs: [ "create", "get", "list", "watch", "delete", "deletecollection", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "list" ]
