image:
  name: consul-kv-operator
  tag: latest

serviceaccount:
    name: consul-kv-operator-service-account

role:
  name: consul-kv-operator-role

# Keep in sync with consul-kv-operator.py
crd:
  group: extensions.logistic.com
  pluralName: ckvs
