name: Build Docker image and Helm Chart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: v3.5.0

      - name: Packer init
        run: packer init .
        env:
          PACKER_LOG: 1

      - name: Packer validate
        run: packer validate -syntax-only packer.pkr.hcl
        env:
          PACKER_LOG: 1

      - name: Build docker image
        run: packer build -var image_tag=1.0.0-ci -except=docker-push .
        env:
          PACKER_LOG: 1
          PKR_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          PKR_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PKR_VAR_ecr_url: ${{ secrets.AWS_ECR_URL }}

      - name: Helm Lint
        run: helm lint ./helm

      - name: Helm template
        run: helm template ./helm
